author: vitaliy0x1
date: 2020/01/21
description: Detects AWS Config Service disabling
detection:
  condition: selection_source AND events
  events:
  - eventName:
    - DeleteDeliveryChannel
    - StopConfigurationRecorder
  selection_source:
  - eventSource: config.amazonaws.com
falsepositives:
- Valid change in AWS Config Service
id: 07330162-dba1-4746-8121-a9647d49d297
level: high
logsource:
  service: cloudtrail
service: cloudtrail
status: experimental
tags:
- attack.defense_evasion
- attack.t1562.001
title: AWS Config Disabling Channel/Recorder
